clear;
clc;
tic
image=imread('E:\GAC_Files\PW6glider\03_MEASUREMENT_images\cam_1\frame_000192.bmp');
[imageWidth,imageHeight]=size(image);
aspectRatio=int64(imageWidth/imageHeight);
xcornerguess=564;
ycornerguess=590;
cascadeDetectorFilePath='E:\GitHub\Masters_Work\XML_Files\markerDetector.xml';
markerCornerGuess=marker_detection(image,imageWidth,imageHeight,aspectRatio,xcornerguess,ycornerguess,cascadeDetectorFilePath);
toc